#!/usr/bin/env python

Import("env")
Import("env_modules")

env_modules.add_source_files(env.modules_sources, "*.cpp")  # just add all cpp files to the build
env_modules.add_source_files(env.modules_sources, "unqlite/*.c")  # add unqlite sources (v.1.1.9)
